---
title: "Introduction to R programming"
date: 2024/04/03
categories: BDSI Workshop
engine: knitr
---


## Welcome 👋

This is a training workshop for staff and students affiliated with the Australian National University (ANU) offered by the ANU Biological Data Science Institute (BDSI).

The workshop is designed to introduce participants to the fundamentals of using R for basic computations. It is suitable for individuals with no prior experience in R or those seeking a refresher in R. Familiarity with basic summary statistics (mean, median, standard deviation, quartiles, etc.) is assumed. It's important to note that this workshop alone is not sufficient to practice data analysis. Attendees are encouraged to also participate in the Data Wrangling with R (Part 1) and Data Visualization with R (Part 1) workshops to acquire essential skills for contemporary data wrangling and visualization practices.

## Learning objectives 

Upon completion of the workshop, participants should be able to:

{{< include slides/_learning-objectives.qmd >}}

## Preperation 

You will need a laptop that can connect to the internet during the workshop. Please ensure that you download and install 

- the latest version of [R](https://cran.csiro.au/),
- the latest version of [RStudio Desktop](https://posit.co/download/rstudio-desktop/), 
- (Optional) [Slack](https://slack.com/intl/en-au) (alternatively you can use the web version), and 

{{< fa hand-holding-medical >}} If you are having issues, ask in the slack channel or talk to the teaching team during the workshop.

::: {.callout-note icon=false style="width:100%"}

## <i class='fab fa-slack'></i> [Slack workspace (Optional)]{#slack}

We use Slack to facilitate communication between workshop participants and the teaching team. 

::: w-100

[<button class="button">Join ANU Learning Data Slack Community</button>](https://join.slack.com/t/anulearningdata/signup){.no-decoration}

:::

- You must use your ANU email to sign up. 
- Use your _full_ name. 
- By joining, you agree to abide by this [**code of conduct**](/slack.html).
- Please **don't direct message the teaching team** in Slack. Your questions are more likely to be answered in the Slack channels rather than in direct messages.

Please note that the teaching team does not necessarily actively monitor or attend to the Slack workspace outside of the workshop.

:::

## Teaching team 

```{css}
#| echo: false
.nav-link.active {
  background-color: #F5EDDE!important;
  border-bottom-color: #F5EDDE!important;
}

.tab-content {
  background-color: #F5EDDE!important;
}
```



`r photo_path <- "slides/"`



{{< include slides/_team.qmd >}}

## Materials 


The materials can be found [here](/materials.html).