---
title: "Materials"
date: 04/03/2024
engine: knitr
categories: BDSI Workshop
format: 
  html:
    css: 
      - assets/webex.css
      - assets/custom.css
    include-after-body: 
      - assets/webex.js
      - assets/copyonclick.js
filters:
  - webr2
webr: 
  show-startup-message: false    
---

```{r setup, include = FALSE}
library(webexercises)
ex_tabset <- function(id) {
  paste0("[_Exercise ", id, "_](#tabset-1-", id, "-tab){onclick=",
         'document.getElementById(', "'tabset-1-", id, "-tab').click();",
         '}')
}
slide_title <- function(id) {
  paste0("[", 
         rmarkdown::yaml_front_matter(paste0("slides/slide", id, ".qmd"))$title,
         "](slides/slide", id, ".html){target='_blank'}")
}

LOs <- readLines("slides/_learning-objectives.qmd")
LOs <- LOs[LOs!=""]
LOs <- stringr::str_replace(LOs, "- ", "")

checklist <- function(x) {
  paste0("<ul class='checkbox'>", paste(paste0("<li><input type='checkbox'> ", x, "</li>"), collapse = "\n\n"), "</ul>")
}

urlid <- 0
dataurlcopy <- function(url) {
  urlid <<- urlid + 1
  id <- paste0("url", urlid)
  paste0('<button url="', url, '" id="', id, 
         '" onclick="copyURLtoClipboard(', "'", id, "'", ')">{{< fa copy >}}</button>')
}
```




## 🕙 Schedule


Time | Content 
:-----------|:-----------------|
10.00-10.30 | `r slide_title(1)` |     
10.30-10.40 | `r ex_tabset(1)` |     
10.40-10.50 | `r slide_title(2)`  |     
10.50-11.10 | `r ex_tabset(2)` |      
11.10-11.20 | `r slide_title(3)`  |     
11.20-11.40 | `r ex_tabset(3)` |     
11.40-12.00 | `r slide_title(4)`  |     
12.00-12.20 | `r ex_tabset(4)` |     
12.50-13.00 | `r slide_title(5)`  |     


## 📑 Resources

- Learn R Chapter 1: Getting started with R & RStudio [{{< fa link >}}](https://learnr.numbat.space/chapter1){target="_blank"}
- Learn R Chapter 2: R programming basics [{{< fa link >}}](https://learnr.numbat.space/chapter2){target="_blank"}
- Learn R Chapter 3: Troubleshooting and asking for help [{{< fa link >}}](https://learnr.numbat.space/chapter3){target="_blank"}

## 🏋️‍♀️ Exercises

::: {.panel-tabset}

## Exercise 1

```{webr-r}




```

**Using R as a calculator**

Using R either on your laptop or above console, compute the following values and write the answer in the box. 

- What is $(40 + 5) \times 3$?   `r fitb((40 + 5) * 3)`
- What is $\sqrt{2^4 - 7}$?   `r fitb(sqrt(2^4 - 7))`
- What is $\dfrac{e^2 + 1}{2}$ to two decimal places?   `r fitb(round((exp(2) + 1)/2, 2))`
- What is $\log_2(9)$ to two decimal places?   `r fitb(round(log(9, base = 2), 2))`


**Finding new functions**

The following operations were not shown in the slides so you will need to find the relevant functions yourself. How would you find these? Once you find the relevant functions, compute the following values in R and enter the value in the corresponding box.

- What is $10! = 10\times 9 \times 8 \times \cdots \times 2 \times 1$? This operation is referred to as "factorial".   `r fitb(factorial(10))`
- What is $\cos\left(\frac{2}{3}\pi\right) + \sin(-\pi)$ to two decimal places?  `r fitb(round(cospi(2/3 * pi) + sinpi(-pi), 2))`
- The $\lfloor x \rfloor$  denotes the floor function (the largest integer such that it is smaller or equal to $x$) and $\lceil x \rceil$ denotes the ceiling function (the smallest integer such that it is larger or equal to $x$). What is $\lfloor \frac{1}{4} \pi \rfloor + \lceil \pi e \rceil$? `r fitb(floor(1/4 * pi) + ceiling(pi * exp(1)))`


**Installing R packages**

- Which function installs an R package on CRAN? `r mcq(c(answer = "install.pacakges", "library"))`
- Which function loads an R package into your system? `r mcq(c("install.pacakges", answer = "library"))`
-  On your own laptop, install the following packages: 
  - `praise`, 
  - `readr`, 
  - `reprex`,
  - `sessioninfo`.

- What function is in the `praise` package? `r fitb("praise")` Try running this function on your own laptop.

**Reflect on learning objectives**

You should be able to:

`r checklist(LOs[1:3])`

## Exercise 2


```{webr-r}




```

**Download the data**

Download the following datasets.

Filename | Link to data | Download | Info
------ | ---- | ---: | ---:
`branch-water.xlsx` | `r dataurlcopy("branch-water.xlsx")` | <a href='data/branch-water.xlsx' download>{{< fa file-excel >}}</a> | [{{< fa info-circle >}}](https://datacommons.anu.edu.au/DataCommons/rest/display/anudc:6254?layout=def%3adisplay){target="_blank"}


Using R either on your laptop or above console, compute the following values and enter your answer in the corresponding box.


**Reflect on learning objectives**

You should be able to:

`r checklist(LOs[4:7])`

## Exercise 3


```{webr-r}




```


**Reflect on learning objective**

You should be able to:

`r checklist(LOs[8])`

## Exercise 4


```{webr-r}




```

Using R either on your laptop or above console, compute the following values and enter your answer in the corresponding box.

**Create basic functions**

**Conditional statements**


**For loops**


**Reflect on learning objectives**

**Create a reproducible example**

You should be able to:

`r checklist(LOs[9:10])`


:::
